name: ✍️ New Epic
description: Create a new epic
title: "[Epic]: "
labels: [Type/Epic]
body:
  - type: dropdown
    id: Related-area
    attributes:
      label: Related Area
      description: Choose the area in Choreo you are reporting the bug against
      options:
       - Area/ManagingDevelopment (Develop, deploy, test, component listing etc.)
       - Area/APIM 
       - Area/Observability 
       - Area/AI 
       - Area/LowCode 
       - Area/Connectors 
       - Area/CodeReuse (Publishing reusable connectors, triggers and other artifact to the marketplace)
       - Area/Samples (Getting started samples)
       - Area/Insights 
       - Area/Auth 
       - Area/Billing 
       - Area/CodeServer 
       - Area/DocSite 
       - Area/Other (None Listed Above)
    validations:
      required: true
  - type: textarea
    id: epic-description
    attributes:
      label: Epic description
      description: Describe the epic
      placeholder: A clear and concise description of what epic is about.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Related tasks
      description: Mention the tasks related to the epic
      value: "- [ ] **Task1** 
              - [ ] **Task2** "
    validations:
      required: false

