name: 🚩 Keep track of a security vulnerability
description: Keeps track of a security vulnerability
title: "[Sec]: "
labels: [Type/SecurityVulnerability]
body:
  - type: markdown
    attributes:
      value: |
        Please do not mention the details about the security vulnerability
  - type: input
    id: Reference
    attributes:
      label: Reference
      description: Email subject sent to choreo-security@wso2.com or any other reference to the issue details.