name: \U0001F6E0 R&D Budget Update Request
description: If you need to allocate budget for an R&D task
title: "[Budget]: "
labels: [Type/Task, Team/PlatformEng, SRE/Budgeting]
body:
  - type: textarea
    id: Reason
    attributes:
      label: Reason
      description: Reason for budget request
    validations:
      required: true
  - type: input
    id: Owner
    attributes:
      label: Owner
  - type: input
    id: resource-group
    attributes:
      label: Related resource group in choreo-rnd-001 subscription
  - type: textarea
    id: resources
    attributes:
      label: Resources to be created
  - type: input
    id: budget-increase
    attributes:
      label: Estimated budget increase per month
  - type: input
    id: resource-expiry
    attributes:
      label: Resource expiration date