on:
  issues:
    types: [opened]
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var body = context.payload.issue.body
            var words = body.split(/\s+/g)
            console.log(words)
            for (var i = 0; i < words.length - 1; i++) {
                var word = words[i]
                if(word.startsWith('Area/')) {
                    console.log(label)
                    github.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [label]
                     })
                    break 
                }
            }
            for (var i = 0; i < words.length - 1; i++) {
                var word = words[i]
                if(word.startsWith('Env/')) {
                    console.log(label)
                    github.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [label]
                     })
                    break 
                }
            }
