on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    if: ${{ !(contains(github.event.issue.labels.*.name, 'Resolution/Fixed') || 
          contains(github.event.issue.labels.*.name, 'Resolution/Duplicate') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Postponed') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Invalid') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Moved') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Cannot Reproduce') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Won’t Fix') ||
          contains(github.event.issue.labels.*.name, 'Resolution/Not a bug')) }}
    steps:
      - run:  echo '${{ toJSON(github) }}'
      - run:  echo Resolution label is not set $github.event
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is NOT closed with a proper **Resolution label**. Make sure to add it before closing. Issue is reopened.
      - run: gh issue reopen $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}    
