on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issue.labels.*.name, 'Resolution/Fixed') }}
    steps:
      - run: echo Resolution label is not set


