on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - uses: actions/github-script@v4
        with:
          script: |
            var labels = context.payload.issue.labels.*.name
            console.log(labels);
            for (var i = 0; i < labels.length; i++) {
                var label = labels[i]
                if(label.startsWith('Resolution/')) {
                    console.log('resolution label found');
                    break 
                }
            }
              
