on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.issues.labels.*.name, 'Resolution/.*') }}
    steps:
      - run: echo ${github.event.issues.labels.*.name}
      - run: echo Resolution label is not set


