name: Comment when opened
on:
  issues:
    types:
      - closed
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue reopen $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
